apiVersion: v1
kind: Service
metadata:
  name: preparedata-service
spec:
  selector:
    app: preparedata
  ports:
  - protocol: TCP
    port: 8000   # Cluster-internal port
    targetPort: 8000  # Container's exposed port
  clusterIP: None  # Headless service (for direct pod-to-pod communication)
